{"name": "Проверка если создать пользователя с логином, который уже есть, возвращается ошибка.", "status": "passed", "parameters": [{"name": "login", "value": "'hdsnwtwuqe'"}, {"name": "password_1", "value": "'ijzrfhoszm'"}, {"name": "first_name_1", "value": "'dnezctydqh'"}, {"name": "password_2", "value": "'zvddjhgbsx'"}, {"name": "first_name_2", "value": "'vfaetrcnji'"}], "start": 1733577390409, "stop": 1733577393318, "uuid": "a52c8639-9bfd-432e-ac2b-eba8c18121d3", "historyId": "41623756e1fcec024b55b2cb7285d4ca", "testCaseId": "72bdb8fc5ec76eb90108b3e6bcaa6f49", "fullName": "tests.courier.test_create_courier.TestCreateCourier#test_not_unique_login", "labels": [{"name": "parentSuite", "value": "tests.courier"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "192.168.1.4.non-exists.ptr.local"}, {"name": "thread", "value": "75210-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.courier.test_create_courier"}]}